### ISSUE TITLE
Spectron 测试在 Linux Runner 中报错

### ISSUE THREAD

**Issue by neatfx** [neatfx/tiny-evt#14]
原因：缺少 headless 运行环境支持

安装 xvfb 解决

```yaml
      # With headless
      - name: Test Electron App @ Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install xvfb
          xvfb-run --auto-servernum npm run spectron
```
